# Generated by Django 4.1.6 on 2023-02-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dastur',
            name='shartnoma',
            field=models.FileField(blank=True, null=True, upload_to='shartnoma'),
        ),
    ]
